export function generateMockArticles(sessionId: string, query: string) {
  const lowerQuery = query.toLowerCase();
  
  const isAI = lowerQuery.includes("ai") || lowerQuery.includes("openai") || lowerQuery.includes("anthropic") || lowerQuery.includes("agent") || lowerQuery.includes("llm");
  const isNvidia = lowerQuery.includes("nvidia");
  const isSolar = lowerQuery.includes("solar") || lowerQuery.includes("energy");
  const isVector = lowerQuery.includes("vector") || lowerQuery.includes("database");
  
  let officialArticles: Array<{
    id: string;
    sessionId: string;
    title: string;
    url: string;
    domain: string;
    category: "official" | "trusted";
    score: number;
    snippet: string;
    isApproved: boolean;
    defaultSelected: boolean;
    userSelected: boolean;
    publishedDate: string;
  }> = [];
  
  let trustedArticles: typeof officialArticles = [];

  if (isNvidia) {
    officialArticles = [
      { id: `${sessionId}-o1`, sessionId, title: "NVIDIA Announces Next-Generation Blackwell Ultra Architecture", url: "https://nvidianews.nvidia.com/news/nvidia-blackwell-ultra", domain: "nvidianews.nvidia.com", category: "official", score: 0.98, snippet: "NVIDIA today announced the Blackwell Ultra architecture, delivering unprecedented performance for AI training and inference workloads at scale.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-10" },
      { id: `${sessionId}-o2`, sessionId, title: "NVIDIA Q4 FY2026 Financial Results Exceed Expectations", url: "https://investor.nvidia.com/news-details/2026/03/01/q4-results", domain: "investor.nvidia.com", category: "official", score: 0.96, snippet: "NVIDIA reported record quarterly revenue of $42.1 billion, driven by continued strong demand for data center GPUs.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-01" },
      { id: `${sessionId}-o3`, sessionId, title: "NVIDIA CUDA 13.0 Developer Toolkit Released", url: "https://developer.nvidia.com/cuda-13-0-release", domain: "developer.nvidia.com", category: "official", score: 0.94, snippet: "The latest CUDA toolkit brings significant performance improvements for deep learning frameworks and scientific computing.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-02-28" },
      { id: `${sessionId}-o4`, sessionId, title: "NVIDIA Partnerships with Major Cloud Providers for AI Infrastructure", url: "https://blogs.nvidia.com/blog/cloud-partnerships-2026", domain: "blogs.nvidia.com", category: "official", score: 0.91, snippet: "NVIDIA announces expanded partnerships with AWS, Azure, and Google Cloud for next-generation AI infrastructure deployment.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-02-20" },
      { id: `${sessionId}-o5`, sessionId, title: "NVIDIA Launches DRIVE Thor Automotive SoC for 2027 Vehicles", url: "https://nvidianews.nvidia.com/drive-thor-launch", domain: "nvidianews.nvidia.com", category: "official", score: 0.89, snippet: "NVIDIA's DRIVE Thor system-on-chip will power next generation autonomous vehicles from multiple automakers.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-02-15" },
    ];
    trustedArticles = [
      { id: `${sessionId}-t1`, sessionId, title: "NVIDIA's Dominance in AI Chips: Analysis of Market Position", url: "https://techcrunch.com/2026/03/12/nvidia-ai-chip-dominance", domain: "techcrunch.com", category: "trusted", score: 0.95, snippet: "An in-depth look at how NVIDIA maintains its commanding lead in AI semiconductor market share, with over 80% of data center GPU revenue.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-12" },
      { id: `${sessionId}-t2`, sessionId, title: "How NVIDIA's Blackwell Changes the AI Landscape", url: "https://arstechnica.com/ai/2026/nvidia-blackwell-analysis", domain: "arstechnica.com", category: "trusted", score: 0.93, snippet: "Technical deep-dive into the architectural improvements of NVIDIA's Blackwell platform and implications for large model training.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-11" },
      { id: `${sessionId}-t3`, sessionId, title: "NVIDIA vs AMD: The AI Accelerator War Heats Up", url: "https://wired.com/story/nvidia-amd-ai-accelerator-2026", domain: "wired.com", category: "trusted", score: 0.90, snippet: "As AMD closes the gap with MI400X, we analyze the competitive landscape for AI accelerators through 2027.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-08" },
      { id: `${sessionId}-t4`, sessionId, title: "Enterprise AI Infrastructure Spending: NVIDIA at the Center", url: "https://venturebeat.com/ai/enterprise-ai-infrastructure-2026", domain: "venturebeat.com", category: "trusted", score: 0.88, snippet: "Enterprise spending on AI infrastructure continues to surge with NVIDIA hardware at the core of most deployments.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-03-05" },
      { id: `${sessionId}-t5`, sessionId, title: "NVIDIA's Software Ecosystem: CUDA's Moat Explained", url: "https://stratechery.com/nvidia-cuda-moat", domain: "stratechery.com", category: "trusted", score: 0.86, snippet: "Ben Thompson analyzes how NVIDIA's CUDA software ecosystem creates a durable competitive advantage beyond hardware.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-03-03" },
    ];
  } else if (isAI) {
    officialArticles = [
      { id: `${sessionId}-o1`, sessionId, title: "OpenAI Releases GPT-5 with Enhanced Reasoning Capabilities", url: "https://openai.com/blog/gpt-5", domain: "openai.com", category: "official", score: 0.99, snippet: "OpenAI today unveiled GPT-5, featuring groundbreaking improvements in mathematical reasoning, code generation, and multi-modal understanding.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-13" },
      { id: `${sessionId}-o2`, sessionId, title: "OpenAI Operator: Autonomous Web Agent Now Generally Available", url: "https://openai.com/blog/operator-ga", domain: "openai.com", category: "official", score: 0.97, snippet: "OpenAI's computer-using agent Operator has graduated from research preview to general availability for all ChatGPT subscribers.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-05" },
      { id: `${sessionId}-o3`, sessionId, title: "Anthropic Claude 4 Sonnet: Safety and Capability Update", url: "https://anthropic.com/news/claude-4-sonnet", domain: "anthropic.com", category: "official", score: 0.95, snippet: "Anthropic releases Claude 4 Sonnet with improved Constitutional AI training, enhanced long-context performance, and new tool use capabilities.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-02-28" },
      { id: `${sessionId}-o4`, sessionId, title: "Google DeepMind Gemini Ultra 2.0 Multimodal Benchmarks", url: "https://deepmind.google/blog/gemini-ultra-2", domain: "deepmind.google", category: "official", score: 0.93, snippet: "Gemini Ultra 2.0 sets new state-of-the-art results on MMLU, HumanEval, and visual reasoning benchmarks.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-02-22" },
      { id: `${sessionId}-o5`, sessionId, title: "Meta AI Llama 4 Open Source Release Announcement", url: "https://ai.meta.com/blog/llama-4-open-source", domain: "ai.meta.com", category: "official", score: 0.91, snippet: "Meta releases Llama 4 family of models under a permissive open source license, including a 405B parameter version.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-02-18" },
    ];
    trustedArticles = [
      { id: `${sessionId}-t1`, sessionId, title: "The State of AI Agents in 2026: Capabilities and Limitations", url: "https://techcrunch.com/2026/ai-agents-state-2026", domain: "techcrunch.com", category: "trusted", score: 0.96, snippet: "A comprehensive survey of the AI agent landscape, from simple tool-using models to fully autonomous computer-use systems.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-14" },
      { id: `${sessionId}-t2`, sessionId, title: "Enterprise AI Adoption: 78% of Fortune 500 Now Using LLMs", url: "https://fortune.com/ai-enterprise-adoption-2026", domain: "fortune.com", category: "trusted", score: 0.94, snippet: "A new survey from Fortune reveals dramatic acceleration in enterprise AI adoption across industries in the past 12 months.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-10" },
      { id: `${sessionId}-t3`, sessionId, title: "GPT-5 vs Claude 4 vs Gemini 2: Independent Benchmark Review", url: "https://scale.com/research/frontier-model-evals-2026", domain: "scale.com", category: "trusted", score: 0.92, snippet: "Scale AI's independent evaluation team runs frontier models through a comprehensive battery of real-world capability tests.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-14" },
      { id: `${sessionId}-t4`, sessionId, title: "AI Safety Regulations: EU AI Act Implementation Update", url: "https://wired.com/eu-ai-act-implementation-2026", domain: "wired.com", category: "trusted", score: 0.88, snippet: "A detailed look at how the EU AI Act is being implemented and what it means for AI companies operating in Europe.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-03-07" },
      { id: `${sessionId}-t5`, sessionId, title: "The Economic Impact of AI Productivity Tools: A 2026 Analysis", url: "https://hbr.org/ai-productivity-economic-impact", domain: "hbr.org", category: "trusted", score: 0.85, snippet: "Harvard Business Review analysis of productivity gains from AI tools across knowledge-worker industries.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-03-02" },
    ];
  } else if (isSolar) {
    officialArticles = [
      { id: `${sessionId}-o1`, sessionId, title: "IEA: Solar Power Now Cheapest Electricity in History", url: "https://iea.org/news/solar-cheapest-electricity-2026", domain: "iea.org", category: "official", score: 0.98, snippet: "The International Energy Agency reports solar PV has achieved record low costs below $15/MWh in optimal regions.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-10" },
      { id: `${sessionId}-o2`, sessionId, title: "DOE Announces $5 Billion Grid-Scale Solar Storage Initiative", url: "https://energy.gov/news/solar-storage-initiative-2026", domain: "energy.gov", category: "official", score: 0.96, snippet: "The U.S. Department of Energy launches a major funding initiative to accelerate deployment of solar-plus-storage systems.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-05" },
      { id: `${sessionId}-o3`, sessionId, title: "NREL Achieves 40% Efficiency in Perovskite-Silicon Tandem Cells", url: "https://nrel.gov/news/perovskite-efficiency-record", domain: "nrel.gov", category: "official", score: 0.94, snippet: "National Renewable Energy Laboratory researchers break efficiency record for commercially-viable perovskite-silicon tandem solar cells.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-02-28" },
      { id: `${sessionId}-o4`, sessionId, title: "EPA Solar Energy Environmental Benefits Report 2026", url: "https://epa.gov/reports/solar-benefits-2026", domain: "epa.gov", category: "official", score: 0.90, snippet: "Annual EPA report quantifying the environmental and public health benefits of the expanding US solar fleet.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-02-20" },
    ];
    trustedArticles = [
      { id: `${sessionId}-t1`, sessionId, title: "The Solar Energy Revolution: How 2026 Became a Turning Point", url: "https://technologyreview.com/solar-revolution-2026", domain: "technologyreview.com", category: "trusted", score: 0.95, snippet: "MIT Technology Review examines how supply chain improvements, perovskite innovation, and policy changes made 2026 a watershed year for solar.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-12" },
      { id: `${sessionId}-t2`, sessionId, title: "Floating Solar: The Next Frontier in Renewable Energy", url: "https://nature.com/articles/floating-solar-2026", domain: "nature.com", category: "trusted", score: 0.93, snippet: "Nature Energy explores the rapid growth of agrivoltaic and floating solar installations and their dual-use potential.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-08" },
      { id: `${sessionId}-t3`, sessionId, title: "Solar Industry Employment Surpasses Oil & Gas for First Time", url: "https://bloomberg.com/green/solar-employment-milestone", domain: "bloomberg.com", category: "trusted", score: 0.91, snippet: "Bloomberg NEF analysis shows solar energy employment has exceeded fossil fuel industry jobs in the United States.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-05" },
      { id: `${sessionId}-t4`, sessionId, title: "Utility-Scale Solar Investment Trends: Q1 2026 Review", url: "https://woodmac.com/solar-investment-q1-2026", domain: "woodmac.com", category: "trusted", score: 0.87, snippet: "Wood Mackenzie's quarterly review of global utility-scale solar investment flows and project pipeline.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-03-02" },
    ];
  } else if (isVector) {
    officialArticles = [
      { id: `${sessionId}-o1`, sessionId, title: "Pinecone Serverless V3: Next-Generation Vector Search", url: "https://pinecone.io/blog/serverless-v3", domain: "pinecone.io", category: "official", score: 0.97, snippet: "Pinecone launches Serverless V3 with dramatically improved latency, better metadata filtering, and sparse-dense hybrid search.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-11" },
      { id: `${sessionId}-o2`, sessionId, title: "Weaviate 1.28 Release: GraphQL Improvements and Vector Compression", url: "https://weaviate.io/blog/release-1-28", domain: "weaviate.io", category: "official", score: 0.95, snippet: "Weaviate's latest release brings 60% vector storage compression with minimal recall degradation using advanced PQ techniques.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-07" },
      { id: `${sessionId}-o3`, sessionId, title: "pgvector 0.8.0: Native PostgreSQL Vector Extensions", url: "https://github.com/pgvector/pgvector/releases/0.8.0", domain: "github.com", category: "official", score: 0.92, snippet: "pgvector 0.8.0 introduces HNSW index improvements, sparse vectors, and better performance for high-dimensional spaces.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-04" },
      { id: `${sessionId}-o4`, sessionId, title: "Qdrant Cloud Enterprise: Multi-tenant Vector Database", url: "https://qdrant.tech/blog/cloud-enterprise-launch", domain: "qdrant.tech", category: "official", score: 0.90, snippet: "Qdrant announces its enterprise cloud offering with role-based access control, audit logging, and SLA guarantees.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-02-25" },
    ];
    trustedArticles = [
      { id: `${sessionId}-t1`, sessionId, title: "The Vector Database Landscape in 2026: A Comprehensive Guide", url: "https://towardsdatascience.com/vector-databases-2026-guide", domain: "towardsdatascience.com", category: "trusted", score: 0.94, snippet: "An updated analysis of the vector database ecosystem, comparing performance, features, and use cases across leading solutions.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-13" },
      { id: `${sessionId}-t2`, sessionId, title: "RAG in Production: Lessons from Scaling Vector Search", url: "https://www.databricks.com/blog/rag-production-vector-search", domain: "databricks.com", category: "trusted", score: 0.92, snippet: "Databricks engineering shares production learnings from deploying RAG systems at scale with vector databases.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-09" },
      { id: `${sessionId}-t3`, sessionId, title: "Benchmarking Vector Databases: ANN Performance in 2026", url: "https://jina.ai/benchmarks/vector-db-2026", domain: "jina.ai", category: "trusted", score: 0.90, snippet: "Comprehensive benchmarks comparing ANN search performance across Pinecone, Weaviate, Qdrant, Milvus, and pgvector.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-06" },
      { id: `${sessionId}-t4`, sessionId, title: "Multimodal Vector Search: Images, Audio, and Text in One Database", url: "https://huggingface.co/blog/multimodal-vector-search", domain: "huggingface.co", category: "trusted", score: 0.87, snippet: "How modern vector databases are evolving to support multimodal embeddings from images, audio, and structured data.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-03-02" },
    ];
  } else {
    officialArticles = [
      { id: `${sessionId}-o1`, sessionId, title: `Official Report: Key Developments in ${query.substring(0, 40)}`, url: "https://source.example.com/official-report-1", domain: "source.example.com", category: "official", score: 0.97, snippet: "Comprehensive official report covering the most significant recent developments, policy changes, and technical advances in this domain.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-14" },
      { id: `${sessionId}-o2`, sessionId, title: `Industry Statement: Current Landscape and Future Outlook`, url: "https://source.example.com/industry-statement", domain: "source.example.com", category: "official", score: 0.94, snippet: "Official industry body statement on market conditions, regulatory environment, and strategic priorities for the coming year.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-10" },
      { id: `${sessionId}-o3`, sessionId, title: `Regulatory Update: New Guidelines and Compliance Requirements`, url: "https://regulator.example.gov/guidelines-2026", domain: "regulator.example.gov", category: "official", score: 0.91, snippet: "Updated regulatory framework and compliance requirements for organizations operating in this sector.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-07" },
      { id: `${sessionId}-o4`, sessionId, title: `Q1 2026 Market Data and Statistics Overview`, url: "https://source.example.com/market-data-q1", domain: "source.example.com", category: "official", score: 0.88, snippet: "Latest quarterly market data, growth metrics, and trend analysis from authoritative sources.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-03-01" },
    ];
    trustedArticles = [
      { id: `${sessionId}-t1`, sessionId, title: `In-Depth Analysis: What's Driving Change in This Sector`, url: "https://reuters.com/sector-analysis-2026", domain: "reuters.com", category: "trusted", score: 0.95, snippet: "Reuters investigative analysis of the key forces reshaping this industry, featuring expert commentary and data from leading analysts.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-13" },
      { id: `${sessionId}-t2`, sessionId, title: `Expert Perspectives: Innovation Trends and Disruptors`, url: "https://forbes.com/innovation-trends-2026", domain: "forbes.com", category: "trusted", score: 0.92, snippet: "Forbes collection of expert perspectives on the most impactful emerging innovations and technology disruptors.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-11" },
      { id: `${sessionId}-t3`, sessionId, title: `Research Review: Academic Findings and Industry Implications`, url: "https://nature.com/research-review-2026", domain: "nature.com", category: "trusted", score: 0.89, snippet: "Nature's synthesis of recent academic research papers and their practical implications for industry practitioners.", isApproved: true, defaultSelected: true, userSelected: true, publishedDate: "2026-03-08" },
      { id: `${sessionId}-t4`, sessionId, title: `Market Intelligence: Competitive Dynamics and Investment Signals`, url: "https://bloomberg.com/market-intelligence-2026", domain: "bloomberg.com", category: "trusted", score: 0.86, snippet: "Bloomberg Intelligence analysis of competitive positioning, M&A activity, and investment flows in the sector.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-03-04" },
      { id: `${sessionId}-t5`, sessionId, title: `Future Outlook: Predictions for the Next 18 Months`, url: "https://economist.com/future-outlook-2026", domain: "economist.com", category: "trusted", score: 0.83, snippet: "The Economist's data-driven predictions for how this sector will evolve based on current trajectories and emerging signals.", isApproved: true, defaultSelected: false, userSelected: false, publishedDate: "2026-02-28" },
    ];
  }
  
  return { officialArticles, trustedArticles };
}

export const WORKFLOW_STAGES = [
  { stageId: "analyze", label: "Analyzing query", description: "Understanding the research topic and identifying key entities", orderIndex: 0 },
  { stageId: "domains", label: "Identifying official domains", description: "Finding authoritative and official sources for this topic", orderIndex: 1 },
  { stageId: "expand", label: "Expanding trusted source pool", description: "Broadening the source pool to include trusted external publications", orderIndex: 2 },
  { stageId: "fetch", label: "Fetching candidate URLs", description: "Retrieving potential article URLs from identified sources", orderIndex: 3 },
  { stageId: "extract", label: "Extracting article content", description: "Processing and extracting content from candidate articles", orderIndex: 4 },
  { stageId: "score", label: "Scoring article quality and relevance", description: "Evaluating each article's quality, relevance, and authority", orderIndex: 5 },
  { stageId: "classify", label: "Classifying into official and trusted sources", description: "Categorizing approved articles into official vs trusted buckets", orderIndex: 6 },
  { stageId: "select", label: "Selecting top results", description: "Ranking and selecting the highest quality articles for your report", orderIndex: 7 },
];
